### ISSUE TITLE
Improve "The response channel was closed prematurely." message

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#102]
I see this message quite a bit, and I'm getting it right now on a server where I'm trying to do some load testing.  Can we add some additional information to the logs that helps me know at least what request is causing the error?  As it stands, I currently have no clue how to even begin troubleshooting the log message.

**Comment by bdw429s** [comment]
I'll also add, JMeter doesn't report any erroring requests which makes me wonder if this is really even an error or not.

**Comment by denuno** [comment]
I've always thought that was the client "hanging up rudely" so to speak, and not a real error per se, but maybe something is leaking and that's causing this error and the lock on windows?  I'd expect to see it a lot more often if that were the case, really, but who knows.  FWIW JMeter tests are the kinds of things I'd probably expect to drop connections, depending on what you're doing with them.

**Comment by bdw429s** [comment]
What additional information can we add to the log so we can debug this?  The JMeter test I was running didn't report any errors and was running fine so I wouldn't expect it to be hanging up at all.  I do see this for sure when I _stop_ a JMeter test forcefully but I would expect it then.  If we can get some better logging in place, I can see if it is only happening with a specific request to help narrow down the issue.

**Comment by denuno** [comment]
What's the stacktrace for this again?  That'd have our options for logging it "within the flow" so to speak.  The next release will have some type of extra logging (either access or request, can't recall offhand), which might help in the troubleshooting as well-- I just gotta get those commits pushed, which I'll try to do today (and get that jvm arg PR in too).

**Comment by bdw429s** [comment]
There is no stack trace. That message in the issue title is literally all I get.  You can see why I'm looking for more info! :)

**Comment by denuno** [comment]
I'm not sure that it'll help much, but FWIW the latest snapshot adds some more logging options, perhaps you can compare the timing of the error with requests... dunno where that message is coming from, I'd expect something like https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/TruncatedResponseException.java

**Comment by bdw429s** [comment]
Confirmed this is now the message:

```bash
[ERROR] runwar.server: The response channel was closed prematurely.  Request path: /index.cfm status-code: 200
```
