### ISSUE TITLE
3.8.0 snapshot breaks rewrites due to web-inf directory mismatch

### ISSUE THREAD

**Issue by gpickin** [cfmlprojects/runwar#106]
INFO: org.tuckey.web.filters.urlrewrite.utils.Log DEBUG: logLevel set to DEBUG
Mar 19, 2018 3:29:39 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: confPath set to /WEB-INF/urlrewrite..xml
Mar 19, 2018 3:29:39 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: statusEnabledConf set to true
Mar 19, 2018 3:29:39 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter ERROR: unable to find urlrewrite conf file at /WEB-INF/urlrewrite..xml

It looks for it in the wrong directory. 
The file is there

It has 2 dots ( not right ) in the name of the file, but that is what it's looking for.
But it cannot locate the file.

**Comment by bdw429s** [comment]
@gpickin Can you run a `--debug` start just to confirm that CommandBox isn't passing the config path to Runwar with the extra dots already in it?

**Comment by gpickin** [comment]
well, when i reverted to runwar 3.7 it worked fine with just 1 dot
so i assumed it was runwar 3.8.0

**Comment by gpickin** [comment]
It creates the file with 2 dots, and looks for it with 2 dots, so thats another issue... but still exists.
I think the web-inf issue is the same reason Adobe CF isn't working for you @bdw429s

**Comment by gpickin** [comment]
CommandBox:cms.avoyatravel.com> start --debug --console --trace
Looking for server JSON file by convention: C:\www\cms.avoyatravel.com\/server.json
webroot defaulted to location of server's JSON file: C:\www\cms.avoyatravel.com\

Running package script [preServerStart].
> rm .engine/lucee5/WEB-INF/lucee-server/felix-cache --recurse --force

start server in - C:\www\cms.avoyatravel.com\
server name - dev-cms.avoyatravel.com
server config file - C:\www\cms.avoyatravel.com\/server.json
Contacting ForgeBox to determine the latest & greatest version of [lucee 5]...  Use an exact 'cfengine' version to skip this check.
OK, [lucee 5.2.6+60] it is!
WAR/zip archive already installed.
Server start command: C:\www\jre\bin\java.exe
    -Xmx1024m
    -Dlucee-extensions=465E1E35-2425-4F4E-8B3FAB638BD7280A
    -jar C:\Users\gavinpickin\.CommandBox\lib\runwar-3.8.0-SNAPSHOT.jar
    --background=false
    --host 127.0.0.1
    --stop-port 60752
    --processname dev-cms.avoyatravel.com [lucee 5.2.6+60]
    --log-dir C:/www/cms.avoyatravel.com/.engine/lucee5//logs
    --server-name dev-cms.avoyatravel.com
    --tray-icon C:\www\cms.avoyatravel.com\modules\contentbox\content\ContentBox_300.png
    --tray-config C:\Users\gavinpickin\.CommandBox/server/EECB99A13E520F8392B6EED7F5140D57-dev-cms.avoyatravel.com/trayOptions.json
    --tray-enable true
    --directoryindex true
    --timeout 240
    --proxy-peeraddress true
    --debug true
    --servlet-rest-mappings ___DISABLED___
    --log-level TRACE
    --cfengine-name lucee
    -war C:\www\cms.avoyatravel.com\
    --web-xml-path C:/www/cms.avoyatravel.com/.engine/lucee5//WEB-INF/web.xml
    --http-enable true
    --ssl-enable false
    --ajp-enable false
    --open-browser true
    --open-url http://127.0.0.1:51789
    --port 51789
    --urlrewrite-enable true
    --urlrewrite-file C:\Users\gavinpickin\.CommandBox\cfml\system\config\urlrewrite.xml
The server for C:\www\cms.avoyatravel.com\ is starting on http://127.0.0.1:51789 ...
[main] INFO runwar.Server - Logging output to C:\www\cms.avoyatravel.com\.engine\lucee5\logs\server.out.txt
[main] INFO runwar.Server - Logging errors to C:\www\cms.avoyatravel.com\.engine\lucee5\logs\server.err.txt
******************************************************************************
Starting - port:51789 stop-port:60752 warpath:file:/C:/www/cms.avoyatravel.com/
context: /  -  version: 3.8.0
web-dirs: C:\www\cms.avoyatravel.com
Log Directory: C:\www\cms.avoyatravel.com\.engine\lucee5\logs
******************************************************************************
[main] INFO runwar.Server - Adding additional lib dir of: C:\www\cms.avoyatravel.com\.engine\lucee5\WEB-INF/lib
Mar 19, 2018 4:31:44 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.8.Final
Mar 19, 2018 4:31:44 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.8.Final
Runwar: Serving content from C:\www\cms.avoyatravel.com
[main] INFO runwar.Server - welcome pages in deployment manager: [index.cfm, index.lucee, index.html, index.htm]
[main] INFO runwar.Server - Overriding web.xml rest mappings with [___DISABLED___]
[main] INFO runwar.Server - Added rest mapping: ___DISABLED___ to RESTServlet
===================================================================
SERVER CONTEXT
-------------------------------------------------------------------
- config:C:\www\cms.avoyatravel.com\.engine\lucee5\WEB-INF\lucee-server\context
- loader-version:6.0
- core-version:5.2.6.60-SNAPSHOT
===================================================================

2018-03-19 16:31:46.795 start reading config
2018-03-19 16:31:46.807 fixed LFI
2018-03-19 16:31:46.807 fixed salt
2018-03-19 16:31:46.809 fixed S3
2018-03-19 16:31:46.810 fixed PSQ
2018-03-19 16:31:46.810 fixed logging
2018-03-19 16:31:46.812 fixed Extension
2018-03-19 16:31:46.814 fixed component mappings
2018-03-19 16:31:46.814 fixed to big felix.log
2018-03-19 16:31:46.814 deploy web context
2018-03-19 16:31:46.848 loaded config
2018-03-19 16:31:46.850 loaded constants
2018-03-19 16:31:46.862 loaded loggers
2018-03-19 16:31:46.863 loaded temp dir
2018-03-19 16:31:46.865 loaded id
2018-03-19 16:31:46.866 loaded version
2018-03-19 16:31:46.867 loaded security
2018-03-19 16:31:46.868 loaded lib
2018-03-19 16:31:47.367 Start CFML Controller
2018-03-19 16:31:47.367 extensions to install defined in env variable or system property:465E1E35-2425-4F4E-8B3FAB638BD7280A
2018-03-19 16:31:47.381 installed extensions:465E1E35-2425-4F4E-8B3FAB638BD7280A
2018-03-19 16:31:47.381 touched monitors
===================================================================
WEB CONTEXT (58970a83d8eb1375b4c67a5d9f7eebf6)
-------------------------------------------------------------------
- config:C:\www\cms.avoyatravel.com\.engine\lucee5\WEB-INF\lucee-web (custom setting)
- webroot:C:\www\cms.avoyatravel.com
- hash:58970a83d8eb1375b4c67a5d9f7eebf6
- label:58970a83d8eb1375b4c67a5d9f7eebf6
===================================================================

2018-03-19 16:31:47.516 fixed LFI
2018-03-19 16:31:47.516 fixed salt
2018-03-19 16:31:47.516 fixed S3
2018-03-19 16:31:47.516 fixed PSQ
2018-03-19 16:31:47.516 fixed logging
2018-03-19 16:31:47.516 fixed Extension
2018-03-19 16:31:47.516 fixed component mappings
2018-03-19 16:31:47.516 fixed to big felix.log
2018-03-19 16:31:47.517 deploy web context
2018-03-19 16:31:47.518 loaded config
2018-03-19 16:31:47.520 loaded constants
2018-03-19 16:31:47.538 loaded loggers
2018-03-19 16:31:47.540 loaded temp dir
2018-03-19 16:31:47.541 loaded id
2018-03-19 16:31:47.542 loaded version
2018-03-19 16:31:47.542 loaded security
2018-03-19 16:31:47.542 loaded lib
[main] INFO runwar.Server - Direct Buffers: true
******************************************************************************
*** starting 'stop' listener thread - Host: 127.0.0.1 - Socket: 60752
******************************************************************************
[main] INFO dorkbox.systemTray.SystemTray - Successfully loaded
Server is up - http-port:51789 stop-port:60752 PID:10828 version 3.8.0
Waiting up to 240 seconds for 127.0.0.1:51789...
Opening browser to...http://127.0.0.1:51789
http://127.0.0.1:51789
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.utils.Log DEBUG: logLevel set to TRACE
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: confPath set to /WEB-INF/urlrewrite..xml
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: statusEnabledConf set to true
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter ERROR: unable to find urlrewrite conf file at /WEB-INF/urlrewrite..xml
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.utils.ServerNameMatcher DEBUG: looking for hostname match on current server name 127.0.0.1
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: checking for status path on /
Mar 19, 2018 4:31:51 PM io.undertow.servlet.spec.ServletContextImpl log
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: urlRewriter engine not loaded ignoring request (could be a conf file problem)

**Comment by bdw429s** [comment]
@denuno I just confirmed with Gavin, CommandBox is passing the arg to Runwar as:
```
--urlrewrite-file C:\Users\gavinpickin\.CommandBox\cfml\system\config\urlrewrite.xml
```
But the logs show the new path is:
```
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: confPath set to /WEB-INF/urlrewrite..xml
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter ERROR: unable to find urlrewrite conf file at /WEB-INF/urlrewrite..xml
```

**Comment by gpickin** [comment]
For a custom file, you see the following

` --urlrewrite-file C:\www\cms.avoyatravel.com\.htaccess
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter DEBUG: confPath set to /WEB-INF/urlrewrite..htaccess
INFO: org.tuckey.web.filters.urlrewrite.UrlRewriteFilter ERROR: unable to find urlrewrite conf file at /WEB-INF/urlrewrite..htaccess`

**Comment by denuno** [comment]
I _think_ this is fixed...

**Comment by bdw429s** [comment]
Rewrites are still broken on the very latest snapshot:
```
ERROR: unable to find urlrewrite conf file at /WEB-INF/urlrewrite.xml
```

**Comment by denuno** [comment]
If I try something like:
```
./gradlew shadow && java -jar dist/libs/runwar-3.8.0-SNAPSHOT.jar -war src/test/resources/war/simple.war/ -b false --urlrewrite-file src/test/resources/urlrewrite.xml -debug true
```
it seems to work, can ya post the other startup params so I can see what's up?

**Comment by bdw429s** [comment]
@denuno Just grab the latest CommandBox snapshot, drop in Runwar and do this:
```start --debug --console --rewritesEnabled```
It will show you the full list of JVM args and you can see the errors right there in the console! :)

**Comment by bdw429s** [comment]
Rewrites seem working OK now in 3.8.1

**Comment by denuno** [comment]
Excellent!
