### ISSUE TITLE
WAR path doesn't work if it points to a zipped archive on Windows

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#11]
> java.io.FileNotFoundException: C:\Users\BRAD~1.DEV\AppData\Local\Temp\my-app.war6415535895778020718\C:\Users\Brad.development\AppData\Local\Temp\my-app.war6415535895778020718\WEB-INF\cftags

I'm guessing there's a base directory getting passed in incorrectly  Starting an exploded war seems to work fine.  So it's just when it gets unzipped to the temp dir that it has issues.

**Comment by bdw429s** [comment]
Still having some troubles with this, but new ones now.  I grabbed the Lucee 5 war to test which is pretty easy to get here:
http://snapshot.lucee.org/rest/update/provider/war/5.0.0.244-SNAPSHOT

The first time I try to start the war with:
```
start warpath=my-war.war
```
The first time, nothing happens and `server status --verbose` shows that the process timed out waiting.  No icon ever appears in the system tray and no java process is left running.  `server log` shows the following error:

```
Exception in thread "main" java.lang.NullPointerException
        at runwar.Server.getJarList(Server.java:697)
        at runwar.Server.startServer(Server.java:271)
        at runwar.Start.main(Start.java:12)
```

Inspecting the directory that the war is expanded into shows that most of the files are missing.  There is only `index.cfm`, `application.cfc`, and `web-inf/web.xml`. None of the jars are copied into the exploded folder.  I assume that explains the error trying load the jars since there is not even an lib folder that gets exploded.

FWI, if I explode the war myself by unzipping it, the server starts, but it usually takes two tries as it times out the first time.  This seems specific to Lucee 5 since it takes a long time on first start.

**Comment by denuno** [comment]
Hmm, I've just been testing runwar itself... it's possible I'm not setting warPath correctly in commandbox.  FWIW, I just tested this on windows using the adobe 2016 war, and it exploded correctly and started the war, which was in a directory with a space in it.  I'll run a cmdbox build with the new jar and give the example above a go and see what the deal is.

**Comment by denuno** [comment]
Alright, I sorted it-- that zip was structured differently than most, so I tweaked the unzip stuff to better handle zips like that, and voila.

**Comment by webonix** [comment]
will 
    box upgrade --latest
pick up these changes?

**Comment by webonix** [comment]
oh - no, it doesn't
```

CommandBox:lucee5.0.0.244-SNAPSHOT-fw1-war> upgrade --latest
Getting latest versioning information from http://integration.stg.ortussolutions.com/artifacts/
Ohh Goody Goody, an update has been found (3.1.0+00335) for your installation (3.0.1+00292)!

This update affects the core underpinnings of CommandBox so we can't automate it for you.
Please download the latest version of CommandBox and replace the binary on your OS.
CommandBox will finish the upgrade for you the first time it is run.

Download URL: http://integration.stg.ortussolutions.com/artifacts/ortussolutions/commandbox/3.1.0/

(Your CLI Loader version is 1.1.0 and the latest is 1.3.2+00335)
CommandBox:lucee5.0.0.244-SNAPSHOT-fw1-war> version -verbose
ERROR

Parameter [loader] has a value of [-verbose] which is not of type [boolean].


CommandBox:lucee5.0.0.244-SNAPSHOT-fw1-war> version --verbose
CommandBox 3.0.1+00292
```

**Comment by bdw429s** [comment]
You need two hyphens for a flag.  I don't think the version command has a verbose passenger though. Just hit that url and download a new binary.

**Comment by webonix** [comment]
sorry - my misunderstanding of upgrades (and not reading what is in front of me)

```
C:\Users\amercer\websites>box
Current version higher than installed version!
  *current: cli.version=1.3.2.4.5.2.018
 installed: cli.version=1.1.0.4.5.2.018

*updating installed version
Library path: C:\Users\amercer\.CommandBox\lib
Initializing libraries -- this will only happen once, and takes a few seconds...
..........
Libraries initialized
updated C:\Users\amercer\.CommandBox!
```
