### ISSUE TITLE
Extra output in logs

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#110]
The console out logs have extra text that doesn't make sense.  
```
server:1240
```
The number changes, but I'm not sure what this means.  Can we remove it?

**Comment by denuno** [comment]
This was still from the stale build, but there are now a few loggers which can be controlled separately as to level -- `runwar.server` (general), `runwar.config` (having to do with config, web.xml parsing, etc.), `runwar.request` (resource mapper logging for aliases and such), and `runwar.security` (for SSL, user auth, etc.) so each line will start with the name of the logger (versus all being RunwarLogger).

So basically, decide what you want to see when in "debug", and we can create a profile that does that.  Or maybe a couple, depending... like personally I don't want to have to look at a rewrite log file when testing rewrites, I want to see them in the console logger, but I could see times where I would want them in a log file.. guess we could think about exposing that to uses too (i.e. just custom log4j config files-- log4j2 uses json which would fit nicer-- but holding off until Lucee makes the move).

**Comment by bdw429s** [comment]
This is no longer present in 3.8.1
