### ISSUE TITLE
ANSI colors for all log levels

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#112]
Server out `trace` logs have some sweet ANSI colors now which I like, but `error`, `info`, and `debug` logs are all still devoid of color.  Can we get colors for all the log levels.  Red for errors, yellow for debug, etc.

**Comment by denuno** [comment]
Maybe hard-coding the colors in will do something... FWIW I had already seen different colors per log entry type, so lemme know if this does something different.  If you have a set of ANSI colors you'd like to see feel free to provide them, I just cut and paste something that had all of them defined and now they're brighter and such so :+1:

**Comment by bdw429s** [comment]
Testing again on 3.8.1 now and the colors are all there.  They look _sweet_.  All the Tuckey stuff is back and it's pretty chatty so I'd like to get that moved to its own log still, but other than that it's looking pretty good.

**Comment by bdw429s** [comment]
![image](https://user-images.githubusercontent.com/584009/38184105-11797020-360b-11e8-928a-4e8871d64731.png)

**Comment by bdw429s** [comment]
Can you help explain why some of these lines seem nested inside two loggers:

```bash
[INFO ] io.undertow.servlet: org.tuckey.web.filters.urlrewrite.Condition DEBUG: not equal operator in use
```

This line starts with 
```bash
[INFO ] io.undertow.servlet: 
```
And then ends with

```bash
org.tuckey.web.filters.urlrewrite.Condition DEBUG: not equal operator in use
```
How is it both `DEBUG` and `INFO` at the same time and showing two separate logging categories?

**Comment by denuno** [comment]
I think it might be the logger Tuckey is using... I have the sources here but haven't looked, it could also be that it's a result of being a filter on a servlet... but that doesn't sound quite right.  More likely a result of being shaded into the same jar.  We can see if the Undertow folks have any ideas, it could be an existing thing... I'd wager it's a result of the customizations though versus Undertow itself (usually it is... not always, but usually. :smiley: ).

**Comment by denuno** [comment]
I'm going to close this one, feel free to add comments if we need to change colors or anything, but we'll cover the other stuff in the more specfic logging tickets.

**Comment by bdw429s** [comment]
@denuno Just wanna say I freaking love the colors on these.  We're slowly but surely whipping these logs into shape.  They're much more relevant and much prettier than ever before! :)

![image](https://user-images.githubusercontent.com/584009/38450729-9ec77630-39e8-11e8-9a31-f84bdcb0b2fb.png)
