### ISSUE TITLE
Log4J warnings on Adobe 2016

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#115]
These warnings don't seem to be breaking anything, but is there anyway to suppress them?  I see these when doing a console start on an Adobe CF 2016 server.  You can see Runwar's Log4 bindings seem to be fighting a bit with Adobe's.

```bash
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/.Command%20Box/lib/runwar-3.8.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/.Command Box/server/DF12A13CA26A49AA1D5D4E79F3CB382F-adobetest/adobe-2016.0.05.303689/WEB-INF/cfusion/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
```

**Comment by denuno** [comment]
Oh yeah, meant to check that, it's supposed to skip adding any more slf4j libs to the classpath when loading.

**Comment by denuno** [comment]
Meh, I just suppressed the message, there's nothing I can do as that's actually Adobe's URL classloader loading that one and I'm not down to add another level of classloading into the mix at this point (what it would take to have them in one spot but not another).
