### ISSUE TITLE
Console out on background start has nested Logging information

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#125]
When I do `start --debug` in CommandBox, the console out that streams while the server starts up looks like this:

```
[INFO ] Runwar: processoutput: [DEBUG] runwar.server: Added websocket context
```

We don't want the first part:
```
[INFO ] Runwar: processoutput: 
```
but do want to keep this part:
```
[DEBUG] runwar.server: Added websocket context
```
Note the actual message is `DEBUG` but is getting re-logged as `INFO`.

**Comment by denuno** [comment]
Theoretically this has been fixed, though it seems like intermittently Adobe just hangs with a request now, lemme know if you see that.

**Comment by bdw429s** [comment]
The double logging is fixed.  We are seeing both Adobe and Lucee hanging on some requests which is a huge blocker.  Also, the rewrite log seems to have stopped working.  I'll open a new ticket for that.
