### ISSUE TITLE
System Tray in CommandBox 4 is not scaled properly on Windows HiDpi display

### ISSUE THREAD

**Issue by jcberquist** [cfmlprojects/runwar#130]
![systemtray](https://user-images.githubusercontent.com/3498220/39063343-a34b99ec-447f-11e8-99c6-338c56ba9c27.png)

@bdw429s suggested I open an issue here. 

On the left is the CommandBox 4 snapshot, and on the right is CommandBox 3.9.2  

This is on a 3840x2160 display at 200% scaling.

**Comment by bdw429s** [comment]
Thanks for the ticket @jcberquist For @denuno 's reference, here is the actual image used on Windows for Lucee servers (it's different for mac)
https://github.com/Ortus-Solutions/commandbox/blob/development/src/cfml/system/config/server-icons/trayicon-lucee-32px.png

**Comment by bdw429s** [comment]
I can confirm on my Windows 10 lappy the icon seems cut off.

![image](https://user-images.githubusercontent.com/584009/39076648-33c102f4-44c2-11e8-839f-1c6c45db0b8d.png)

**Comment by bdw429s** [comment]
For comparison, here's the same thing on my Windows 7 desktop PC

![image](https://user-images.githubusercontent.com/584009/39076686-78a1abf8-44c2-11e8-8c2f-32a9094ec52c.png)

**Comment by bdw429s** [comment]
@jcberquist I mentioned in Slack today that we hadn't touched the system tray stuff.  I was wrong-- Denny told me today that he did upgrade to the latest version of DorkBox (no Ortus relation!) which apparently contained the regression.  If we can't get it fixed, we might just revert the upgrade.

**Comment by bdw429s** [comment]
@denuno Are we just going to revert this for now?

**Comment by bdw429s** [comment]
We reverted DorkBox for now and the icon is no longer cropped off.

**Comment by bdw429s** [comment]
@denuno This can be closed now

**Comment by denuno** [comment]
:+1:
