### ISSUE TITLE
Building Project error with .cfdistrorc

### ISSUE THREAD

**Issue by mjclemente** [cfmlprojects/runwar#151]
I'm a newbie to using this project directly, so please forgive my ignorance.

I cloned it and tried to build it via running `./gradlew` but got an error that `.cfdistrorc` referenced in line 14 of `runwar/gradle/config.gradle` doesn't exist. Here's the full line referenced:

```
def replacedConfigFileText = file("${config.user.home}/.cfdistrorc").text
```

Obviously I don't have the file. Is there somewhere else I should get that from?

Thanks for all the work you do with this!

**Comment by denuno** [comment]
Theoretically working again, please give it a go and holler if not. Thanks!

**Comment by mjclemente** [comment]
Thanks! Build is working now. Appreciate it!
