### ISSUE TITLE
Allow for aliases in web path

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#18]
IIS and Apache etc all have the concept of aliases or virtual directories.  The more local dev we're doing the more of an issue it is not to have this.  Allow some list of paths that map a fake web path to a real path on the file system.

**Comment by gpickin** [comment]
I agree.

**Comment by denuno** [comment]
Would this syntax work:  "/real/path:/virtual/path./real/path:/virtual/path...." ?

**Comment by bdw429s** [comment]
So a comma-delimited list of real/virtual pairs consisting of a colon-delimited list of the real and virtual path?  I don't think we can do colons since Windows OS's will have one of those in their actual path `C:\etc`.  What about a semi-colon?

**Comment by denuno** [comment]
If it's in a string, the colon /should/ be fine, but I haven't tested yet (they should be in strings anyway though, to account for spaces and stuff).

**Comment by bdw429s** [comment]
No, I'm not concerned about the OS parsing of it when we pass the args to Runwar.  I'm saying we can't use a colon as a meta-character if it's also a valid character in the contents of our list items.  Unless, of course, we allow them to escape it, but why not just use a different delimiter.

Take this example:

```
"C:\foo:/foo,D:\bar:/bar"
```

You can't reliably break that string on colons because the actual Windows paths have colons in them too.

**Comment by bdw429s** [comment]
FWIW, I was just adding an alias to Tomcat's `server.xml`. Here's the syntax they use:

```
"/CFIDE=C:\ColdFusion11\cfusion\wwwroot\CFIDE,/WEB-INF=C:\ColdFusion11\cfusion\wwwroot\WEB-INF"`
```

So it's an equals sign to delimit the virtual=real pairs and then commas between multiple pairs.

**Comment by denuno** [comment]
Seems like a good syntax to me, let's do it that way.

**Comment by denuno** [comment]
So now instead of just plain dirs, you can pass aliased ones too, eg: 
`--dirs "/CFIDE=C:\ColdFusion11\cfusion\wwwroot\CFIDE,..."`

**Comment by bdw429s** [comment]
This looks great.  I'm excited to give it a try.  Need to lock down 3.1 soon though (I'm out all next week prior to ITB and dev.Objective ) but I'd like to get all these latest Runwar fixes in for this release as long as they're stable.

**Comment by bdw429s** [comment]
Got a chance to test this today. Opened this ticket: https://github.com/cfmlprojects/runwar/issues/28
