### ISSUE TITLE
Multiple hosts

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#19]
We're run across a few client sites where we can't use CommandBox for local dev because they need multiple domains all pointing to CommandBox/Runwar.  This could come in a hard-coded list of domains that the site needs bound to, or some wildcard setup/all domains on a given IP.  What's the best way to support this?

**Comment by gpickin** [comment]
Not as important as Virtual Directories, but still very useful.

**Comment by denuno** [comment]
Binding is done by IP versus host name, and I think either you can (or you could) pass in 0.0.0.0 to have it bind to all IPs, and then we could change the host attribute to take a list of IPs to bind to individually...

**Comment by bdw429s** [comment]
> Binding is done by IP versus host name
Like, in general?  What happens when I do:
```server start host=foo.com```
Does Runwar not actually use that at all?  In other words, if I also had a host file entry pointing `bar.com` to the same IP as `foo.com`, would the Runwar server still respond to `bar.com`?

In Apache, IIS, etc the request would be reject since the site wasn't bound to that host.

**Comment by denuno** [comment]
I'm pretty sure it does something like IP.getByHostName(name)... I just had another thought though, we do a bunch of links and whatnot using that hostname, I'm not sure how we'd handle that.

You can have a basically unlimited list of hosts per IP, so this problem is currently solvable (well, not the links problem mentioned above) by simply putting the desired host names in the hosts file, and having them all resolve to the same IP.

How would we handle the problem of which host to display and whatnot?  Just pick the first one?  It's not like a request, where we can get the hostname from the request.  :-/

**Comment by bdw429s** [comment]
Are you talking about like what happens when you right click on the tray icon and choose "open site" or something?  It think it's a fair solution to just open the first host.  It would probably be possible to make the menu flyout and have a list of hosts there (as long as they were canonical and didn't have wildcards like `*.foo.com`).  That could even be cool to link to each of the Lucee web administrators.  Probably not worth the effort though.  Those menu items are just some nice-to-haves to help people along.

**Comment by denuno** [comment]
So, we can talk about listening on more than one IP, as that is probably doable, but we need to be clear about what that actually does-- which is just bind the application to an IP (and 1 to 4 ports on that IP, depending on how we want to listen for shutdown, plus SSL and/or AJP).

It won't create extra "web contexts" in Lucee, for example.  That would require the "shared jar" + multiple WAR support, basically.  (Which is doable, but it's a whole other ball of wax.)

Listening on multiple IPs is generally the most handy when you want the same app to respond on both an internal (a loopback) and an external IP.  Other than that, the footprint of undertow is so small, I'd generally recommend separate application instances that can be started/shutdown independently, versus bundling a few together... though I'm not adverse to supporting that at some point.

**Comment by bdw429s** [comment]
Yeah to be clear-- I wasn't suggesting that with this ticket people would be able to spin up more than one site in more than one web root listening on more than one host, etc.  Just that more than one domain would respond.  However, it seems that Runwar is listening to any requests on that IP/port already which takes care of a lot of situations with a host file entry.  I think I originally assumed Runwar behaved like Tomcat where you had to add aliases for each domain you wanted to map to a `<host>`.

**Comment by bdw429s** [comment]
This was a good discussion, but closing it for now since I think we've decided this is outside of the current scope of runwar, which aims to be a more container-based approach where there's a separate process for each server.
