### ISSUE TITLE
Don't wipe server out log every time the server starts

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#20]
It would be nice to keep the contents of the server out log across restarts.

**Comment by denuno** [comment]
Need to make this rolling if so... maybe a 10MB cut off... will have to see what the best option to do this will be, since windows makes that kind of thing hard.

**Comment by bdw429s** [comment]
FWIW, Tomcat doesn't roll it's `catalina.out` log and they call it a "feature".  At least, not while it's running.  They do roll it when you stop/start the server.
