### ISSUE TITLE
Directory aliases don't run CFML code

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#28]
If I create a directory alias with the JVM arg `--dirs "/foo=C:\"` and then start my server, I will correctly see a directory listing of my C:\ drive when I hit `http://localhost/foo`. 
I can also browse static assets successfully such as `http://localhost/foo/bar.txt`

If I attempt to load a CFM file like `http://localhost/foo/baz.cfm`. I will receive an error message that `foo/baz.cfm` was not found in the web root.  The path being passed to the CF engine does not reflect the aliased directory.  I tested with the same result on embedded Lucee 4, Lucee 5, and Adobe 2016.

**Comment by denuno** [comment]
What happens if you add a mapping in the cfml engine admin for the aliased dir?  Is the page found then?

**Comment by bdw429s** [comment]
Yes, if I put in a CF mapping that's the same as the web alias name, Lucee will resolve the file.  I can't test on Adobe CF right now since ACF is broken at the moment and I can't build CommandBox with Runwar `3.4.9` because it doesn't appear to be published in your Maven repo yet.

Do you how the standard web connectors for Apache and Lucee/ACF handle this?  They somehow pass the full path through to the CF engine without needing a CF mapping.
