### ISSUE TITLE
Runwar 3.4.6 breaks Adobe CF engines

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#30]
When updating from Runwar `3.4.5` to `3.4.6`, Adobe CF servers 9, 10, 11, and 2016 no longer work.  The servers start up, hitting a page returns a 404.  If there is an Application.cfc, the error is usually that that file can't be found.  Even the administrator won't load.  Something is messing up the paths being sent to the engine such that Adobe can't locate any of the files on the harddrive.

**Comment by denuno** [comment]
The paths are fine, it's actually the servlet context init params.  What Adobe needs isn't apparently what other stuff needs, so I broke Adobe when fixing other stuff.  Yay!

For some reason Adobe needs coldfusion.compiler.outputDir (in web.xml) to be an absolute path for it to know where to put the compiled classes.

Leaving it as-is, `/WEB-INF/cfclasses`, results in it trying to write class files to /WEB-INF/cfclasses, versus {war directory}/WEB-INF/cfclasses.

For now -- until maybe someone from Adobe can chime in as to what the deal is there-- I'm just setting that param to the full absolute path based on cfengine == 'adobe', so at least we're working again.

**Comment by bdw429s** [comment]
Thanks @denuno !  Shoulds this be closed?

**Comment by denuno** [comment]
Should automagically get closed when I merge this stuff into master.

The snapshot for 3.4.9 is up there if you want to give these latest fixes a spin.
