### ISSUE TITLE
Allow caller to control the new grayed-out top menu item

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#39]
Add a new attribute to the menu items defined in the menu JSON to create an information-only menu item.  This will allow CommandBox to control what's in the top menu item (or if it's there at all).  This will also help people whitelabel a standalone server with custom options, or even add their own divider rows in the menu for organization.

**Comment by bdw429s** [comment]
Mentioned this in Slack too.  Just putting it here so it doesn't get lost.

**Comment by denuno** [comment]
Take a look at the new [tray config options](https://github.com/cfmlprojects/runwar/blob/master/src/runwar/taskbar.json)... theoretically you can set the tooltip, if an item is disabled, as well as give each one a custom image if wanted.

**Comment by bdw429s** [comment]
Noiiiice... a custom image as well.  I'm in love!
