### ISSUE TITLE
New static cache prevents dynamic static assets

### ISSUE THREAD

**Issue by alexskinner** [cfmlprojects/runwar#4]
We are dynamically serving TTF and WOFF files and our URLrewrite.xml is configured to rewrite it.

The code in this commit prevents the servlet handing the request and forces it to be a static asset, I think this caching behaviour should be configurable and by default off

https://github.com/cfmlprojects/runwar/commit/c2939af529e2a3cbbccef97ea1c8936d9098b9ac

**Comment by bdw429s** [comment]
@denuno Any thoughts on this?  This has been preventing PresideCMS from running on CommandBox for a while now.

**Comment by denuno** [comment]
This was fixed a while ago, by defaulting the cache to off.
