### ISSUE TITLE
Add a way to disable the rest servlet, bonus points for also making the paths configurable.

### ISSUE THREAD

**Issue by denuno** [cfmlprojects/runwar#46]
The internal server will add the default "/rest" servlet and mapping when it starts up.  It would be swell if we could disable that behavior.  It would also be nice to be able to bind it to a comma-separated list of paths, instead of just `/rest`.

**Comment by bdw429s** [comment]
This fix is causing an NPE
```
     [exec]   Exception in thread "main" java.lang.NullPointerException
     [exec]   at runwar.Server.startServer(Server.java:419)
```
The code there is
```
for(String path : serverOptions.getServletRestMappings()) {
```

**Comment by bdw429s** [comment]
What would it take to make this setting override the `web.xml` like we do for welcome files?  This could be pretty handy even for wars so people can change or turn off the REST handler since editing their `web.xml` file really isn't easy on a CommandBox server.

**Comment by bdw429s** [comment]
Now that the next version of CommandBox basically doesn't have an internal server any longer-- they're all WAR-based servers, we pretty much have to allow this to override the `web.xml` or it will be useless.

**Comment by denuno** [comment]
Ugh, not the easiest thing to do because Adobe is weird.  

Solved, I think, by checking the servlet name for CFRestServlet (adobe) and RestServlet (lucee), 

Hopefully those are the only names that have been in use for those... I'd rather do it by class than servlet name, but Adobe uses a bootloader to set up all it's servlets, which makes that route an uglier one than this one.

**Comment by bdw429s** [comment]
Thx @denuno.  Can you Pls keep this in a branch until I get CommandBox 3.5 released Tuesday.  Actually, if you could cut a final version of Ruwar 3.5, that would be great and this can be the first thing you commit to the 3.6 snapshot.  I just don't want any last minute development to get pulled into the CommandBox release.

**Comment by denuno** [comment]
I cut 3.5, stopping after the java agent removal, since it seemed like you tested up to there basically.  The cool thing is I didn't fix that snapshot-deleting-upon-release bug, so 3.5-SNAPSHOT is gone, along with the changes that are now in 3.6.  If it broke any builds, "my bad", but it was good here-- though I do need to fix that bad-goodness.

**Comment by bdw429s** [comment]
Thx @denuno.  No worries on the snapshot going away.  I just bumped the CommandBox build to use Runwar 3.5.0 Final and running the final build for CommandBox 3.5.0 now.  (Hey, our versions match!! :)

**Comment by bdw429s** [comment]
@denuno Hey, just trying to follow up on some of these older tickets.  Can you confirm that this should work on the WAR-based servers by overriding the rest servlet mappings in the default `web.xml` that ships with the war?  If so, I'll give it some testing and then finalize the CommandBox portions of actually passing the rest mappings from the user.
