### ISSUE TITLE
Support double-wildcard mapping for SES that uses paths like index.cfm/some/info

### ISSUE THREAD

**Issue by denuno** [cfmlprojects/runwar#47]
You can already do this by adding "/index.cfm/*" as a servlet path in web.xml, but you have to do it for every sub-directory too, e.g. "/blog/index.cfm/*", "/api/index.cfc/*", etc..

If we could do double-wildcard mappings we could just define "*.cfm/*" as a path and have that work.  We can't do that though, the spec only calls for support of one.

Instead we use a servlet filter that mimics that behavior.  The [RegexPathInfoFilter](https://github.com/cfmlprojects/regexpathinfofilter) uses a regex to split the URL into a file path and a PATH_INFO variable accessible via cgi.path_info, before passing the file path along to the servlet to be handled.

You can enable and disable this feature with the command line arg: `--filter-pathinfo-enable=[true|false]`

The regex is configurable, but right now there's no way to change it, if someone wants extensions other than .cfm and .cfc, we can tackle adding an option to configure it then.

**Comment by bdw429s** [comment]
This looks great.  Just tested with the internal Luicee 4.5 server, Lucee 5 war, and Adobe 2016 war and it all works.  Turning off the flag in each server also works as expected.   I think we can stick a fork in this one...
