### ISSUE TITLE
Ability to disable sendfile

### ISSUE THREAD

**Issue by denuno** [cfmlprojects/runwar#5]
Copied from Undertow ticket:

We have recently moved a development environment from Apache+Tomcat to Undertow and have encountered a issue we had previously experienced with Apache as well. When a static file, e.g. Javascript is updated Undertow continues to serve the previous version of the file until it to restarted. In Apache we got around this by using the directive:

EnableSendfile Off
(Details here: http://httpd.apache.org/docs/2.2/mod/core.html#enablesendfile)

in the Apache configuration. I have searched for a similar option in Undertow however it doesn't appear to exist.

This issue seems to also be related to VirtualBox as it only affects files shared with the VM via the vboxfs mount option, however I'm sure there are other situations in which being able to bypass "sendfile" would be useful, hence me raising this enhancement here.

**Comment by denuno** [comment]
I've added a --sendfile-enable false (or just -sendfile false) config option, as well as a --transfer-min-size (-transferminsize) option, so you can either disable sendfile or set a custom transfer minimum size.

**Comment by andrew-dixon** [comment]
@denuno Just to let you know, we build the runwar.jar file, replaced it in the .CommandBox lib directory and then updated the file:

`~/.CommandBox/cfml/system/services/ServerService.cfc`

To have `--sendfile-enabled false` as the last JVM argument and this fixed the issue.

Note the "d" on the end of the argument, had to check the source code to find out it should have that.

**Comment by bdw429s** [comment]
Thanks guys.  I've entered this ticket for CommandBox
https://ortussolutions.atlassian.net/browse/COMMANDBOX-294

**Comment by denuno** [comment]
Awesome Andrew, thanks for verifying that!  I've updated the argument to be --sendfile-enable (removing the "d") for the next release.  We'll address surfacing this setting in CommandBox on the ticket Brad created.
