### ISSUE TITLE
Tray icon not disappearing on Windows when server process killed

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#60]
On Windows 7, if I start a server like so:
```
CommandBox> start --console
```
which effectively starts it in the foreground, and then later I stop it with Ctrl-C, the system tray icon stays showing until I hover over it.  Then it will disappear.  Is there something we can do in the JVM to hide the icon on shutdown of the server process?

Note, stopping a server via the standard runwar `stopServer` is fine-- it's only when the process gets killed externally that it doesn't trigger the UI to update.

**Comment by denuno** [comment]
I tried adding a shutdown hook for the tray at one point, but it just caused hangs and other odd behavior.  I don't see this problem on Linux, not sure about OS X, maybe there's some call that could be made on Windows to cause a tray refresh... hrm, looks like maybe sending a mouse event:

http://www.dotnetsurfers.com/blog/2011/02/16/refreshing-the-windows-system-tray-programmatically

**Comment by denuno** [comment]
Doesn't look fixable:

https://superuser.com/questions/178413/removing-killed-processes-from-windows-taskbar-notification-area

**Comment by bdw429s** [comment]
@denuno I'm not sure-- that link is asking if the OS itself can detect and remove the icons.  In our case, I assumed we'd be able to use a finalizer or shutdown hook to do it from the Java process itself.  I wonder if those fire when the process builder process is destroyed.

**Comment by denuno** [comment]
If the Java process could do it, it would do it, AFAIK.  It removes it on Linux, and I think Mac too, so it seems like we're being bit by this bug.  The weird thing is you'd think a `ctrl+c` would send a soft, versus a hard, shutdown request, which would allow it to remove the icon gracefully, but I see a few other java-related, same-bug type-deals (mentioning ctrl+c)...

**Comment by bdw429s** [comment]
I think I have the ability to intercept the Ctrl-C in this instance and do something other than just killing the process.  I might be able to just run the proper stop code.  I'll give it a test.
