### ISSUE TITLE
Taskbar app has incredibly tiny text in Windows 10

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#65]
This ticket was passed along by Ray Camden in this CommandBox ticket:
https://ortussolutions.atlassian.net/browse/COMMANDBOX-561

> I've noticed on two Windows machines now that the taskbar UI for the server is incredibly small. Near impossible to read on the Surface Book. I can send a screen shot if need be.

**Comment by cfjedimaster** [comment]
Here is a screen shot. I intentionally took a big screen shot so you can see the UI in comparison to more of my screen.

![image](https://cloud.githubusercontent.com/assets/393660/22331007/b2d38436-e38e-11e6-8e9b-e1484a0e3c3a.png)

**Comment by bdw429s** [comment]
Thanks @cfjedimaster I can certainly see how small that is now.   Can you let us know what your screen resolution and monitor size is?  The latter possibly doesn't matter, but I'm curious :)  And do you have any other screen scaling or zooming features enabled?  
Also, I noticed the icon itself in the system tray ironically looks too big and cut off on the right and bottom sides.  Can you confirm that as well?

**Comment by cfjedimaster** [comment]
You're right - never really noticed. So I'm not on THAT machine above right now, I'm on my Dell now, but it has the same problem. 4k resolution. No zooming/scaling.

**Comment by denuno** [comment]
The newest SystemTray should have solved this, going to close for now but reopen if not.
