### ISSUE TITLE
Add SSL cert chain file support

### ISSUE THREAD

**Issue by denuno** [cfmlprojects/runwar#69]
What the subject says, brah.

**Comment by denuno** [comment]
I reworked SSL quite a bit, and we can now support more certificate formats as well as adding, perhaps, chain files and whatnot via the new command line option:

`--ssl-add-certs </path/to/cert,/path/to/cert>`

Which will let you add an arbitrary number of certificate files to the store.  Need to verify this works for the chain files though-- I don't have any handy and haven't had a chance to generate the set of certs needed for a test case.

**Comment by bdw429s** [comment]
@denuno Can you write up some comprehensive docs on the SSL support, how it works, and how to use it?  I've been getting a lot of questions about it lately and I don't really know anything about it.  There's also nothing about the SSL stuff in our official CommandBox docs.  If you can help document what we have, I'll incorporate it.
