### ISSUE TITLE
Websockets Support

### ISSUE THREAD

**Issue by lmajano** [cfmlprojects/runwar#74]
@denuno What would it take to enable the options for activating websocket support: http://undertow.io/undertow-docs/undertow-docs-1.3.0/index.html#websockets

**Comment by bdw429s** [comment]
@lmajano This is a duplicate of ticket https://github.com/cfmlprojects/runwar/issues/53 whcih I have already created for Websocket support.

**Comment by lmajano** [comment]
thanks
