### ISSUE TITLE
Implement the equiv of Tomcat's remoteIPValve

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#80]
A CommandBox user has noticed that their site which is behind a proxy doesn't show the actual end-user's IP address for the cgi remote address variable.  Provide a setting to enable whatever Undertow's equivalent is to pass the original IP through.

**Comment by bdw429s** [comment]
@denuno Any ideas on what this will take.  I can try to do a pull if you can let me know what to put in.

**Comment by denuno** [comment]
Already got it working, tests y todo... that's the b best part, the tests.
 :-)

**Comment by bdw429s** [comment]
lol, awesome!

**Comment by bdw429s** [comment]
https://ortussolutions.atlassian.net/browse/COMMANDBOX-648
