### ISSUE TITLE
Basic auth doesn't set cgi.remote_user

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#83]
Basic auth doesn't set cgi.remote_user

https://ortussolutions.atlassian.net/browse/COMMANDBOX-625

**Comment by bdw429s** [comment]
@denuno Did you check into this one at all?  It seems like it should be a quick and easy thing to fix, but I've googled it at length and for the life of me I can't find any information.  I found the example you used and it doesn't mention anything about configuring the remote user to be available.  There's a remote user exchange attribute class in undertow but I can't find any docs at all on what to do with it.

**Comment by denuno** [comment]
It was a little weird, we still needed to do what we were doing before (adding the handler) but now the cgi vars are set correctly, so ¯\_(ツ)_/¯, we can check into this more when we look at what those security constrains can do for us.
