### ISSUE TITLE
Support rewrites for standalone servers

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#9]

**Comment by denuno** [comment]
Can you verify that this and the other issues have been resolved when you get a chance?

**Comment by bdw429s** [comment]
Yep, hopping in a plane right now. I'll check it out very soon.

**Comment by bdw429s** [comment]
So far as I can tell, rewrites work now for standalone servers, but have regressed for the embedded server.  Looking at the log shows this:
```
2016-05-09 21:45:21 INFO io.undertow.servlet org.tuckey.web.filters.urlrewrite.UrlRewriteFilter ERROR: unable to find urlrewrite conf file at /WEB-INF/urlrewrite.xml
```
It would seem the xml file is being looked for in the wrong place even though the following params were sent to Runwar:
```
--urlrewrite-enable true
--urlrewrite-file "C:\Users\Brad\.CommandBox\cfml\system\config\urlrewrite.xml"
```

**Comment by bdw429s** [comment]
Is this ready to re-test or still outstanding?

**Comment by denuno** [comment]
I think I fixed this with the last version bump, but I'm about to do another with the fix for those wars you found (though not sure about the signing one).

**Comment by denuno** [comment]
Seems fixed from my testing, reopen if not.

**Comment by bdw429s** [comment]
Yep, seems to be working now for internal servers.
