### ISSUE TITLE
Validation on tray menu tooltips

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#93]
I can't get the default tray options to work no a CommandBox server.  Here is the output to the server log:
```
 Runwar: system tray hook failed.
 Runwar: java.lang.RuntimeException: Tooltip text cannot be longer than 64 characters.
```
Looks like some additional validation is needed.

**Comment by denuno** [comment]
Should be fixed, using ellipsis if longer than 64.
