### ISSUE TITLE
Incorrectly caching static assets when requesting files with incorrect casing

### ISSUE THREAD

**Issue by elpete** [cfmlprojects/runwar#96]
Not sure if this issue belongs here, but we recently ran in to a strange caching-like bug using CommandBox in the `ortussolutions/commandbox` image.

Given a file system running in Docker (so case-sensitive) like so:

```
| modules_app
|-- My-Module
|---- includes
|------- js
|--------- app.js
```

If I made a request to `http://host:port/modules_app/my-module/includes/js/app.js` (note the difference casing) the request would succeed and load the file.  But if I made any changes to that file and tried to load it from the web server again, it would load the original file.  Only restarting the server or waiting some undetermined amount of time would clear this cache.  When requesting the file with the correct casing, this is not an issue.

Obviously I need to use the correct casing, but I guess I was wondering if the original, incorrect casing file should be served at all in this case?

**Comment by denuno** [comment]
Interesting!  (Interesting how much I've been saying "interesting!" today too-- but that's besides the point)

I'm surprised it served the file at all.  Sounds similar to how it only checks for file existence once by default.  Is this docker on Linux, from Linux (that is, this isn't running in a VM on Windows)?  If it's OS X I remember seeing something similar where the OS X partition was formated with a file system that was case-insensitive (I think the default unless you pick on when installing?  Been a bit) and so basically Docker was too, even though it wasn't, which led to weird things similar to this.

FWIW, we added a `directoryrefresh` parameter to enable having it check for index.cfm after it hadn't been found the first time (Undertow is all about performance, so stuff like that is not done by default) but that only triggers on requests ending with `/`.  Runwar doesn't enable that by default (I don't think) but CommandBox might-- either way, you can verify it's enabled by starting a server with `debug=true`, and once you've done that, trigger the non-refresh and then try hitting a path that ends with `/`, to see if after hitting `/` the non-refreshing file refreshes-- if it does there may be a potential solution.

**Comment by bdw429s** [comment]
@elpete Quick question, are you using URL rewrites?

**Comment by bdw429s** [comment]
I tried to replicate this real quick on Windows, but I can't.  Any changes to the file show up when refreshing.  It must not happen on a case insensitive FS.

**Comment by elpete** [comment]
This was running on Docker for Mac.  The container is definitely case-sensitive while my Mac is not.

**Comment by elpete** [comment]
@bdw429s Yes, we were using URL rewrites

**Comment by denuno** [comment]
Sounds like it's the thing I was talking about.  See these for reference: 

https://github.com/docker/for-mac/issues/320

https://github.com/docker/for-mac/issues/2096

**Comment by denuno** [comment]
I'm going to go ahead and close this, feel free to open it again if it turns out to be something else.
